export const EARL = {
    assertedBy: "http://www.w3.org/ns/earl#assertedBy",
    mainAssertor: "http://www.w3.org/ns/earl#mainAssertor",
    info: "http://www.w3.org/ns/earl#info",
    mode: "http://www.w3.org/ns/earl#mode",
    outcome: "http://www.w3.org/ns/earl#outcome",
    pointer: "http://www.w3.org/ns/earl#pointer",
    result: "http://www.w3.org/ns/earl#result",
    subject: "http://www.w3.org/ns/earl#subject",
    test: "http://www.w3.org/ns/earl#test",
    Assertion: "http://www.w3.org/ns/earl#Assertion",
    Assertor: "http://www.w3.org/ns/earl#Assertor",
    CannotTell: "http://www.w3.org/ns/earl#CannotTell",
    Fail: "http://www.w3.org/ns/earl#Fail",
    NotApplicable: "http://www.w3.org/ns/earl#NotApplicable",
    NotTested: "http://www.w3.org/ns/earl#NotTested",
    OutcomeValue: "http://www.w3.org/ns/earl#OutcomeValue",
    Pass: "http://www.w3.org/ns/earl#Pass",
    Software: "http://www.w3.org/ns/earl#Software",
    TestCase: "http://www.w3.org/ns/earl#TestCase",
    TestCriterion: "http://www.w3.org/ns/earl#TestCriterion",
    TestMode: "http://www.w3.org/ns/earl#TestMode",
    TestRequirement: "http://www.w3.org/ns/earl#TestRequirement",
    TestResult: "http://www.w3.org/ns/earl#TestResult",
    TestSubject: "http://www.w3.org/ns/earl#TestSubject",
    // Instances of TestMode
    automatic: "http://www.w3.org/ns/earl#automatic",
    manual: "http://www.w3.org/ns/earl#manual",
    semiAuto: "http://www.w3.org/ns/earl#semiAuto",
    undisclosed: "http://www.w3.org/ns/earl#undisclosed",
    unknownMode: "http://www.w3.org/ns/earl#unknownMode",
    // Instances of OutcomeValue
    cantTell: "http://www.w3.org/ns/earl#cantTell",
    failed: "http://www.w3.org/ns/earl#failed",
    inapplicable: "http://www.w3.org/ns/earl#inapplicable",
    passed: "http://www.w3.org/ns/earl#passed",
    untested: "http://www.w3.org/ns/earl#untested",
} as const; 
