import { XSD as XSD_NS } from "../ns/mod.js"

export const XSD = {
  string: XSD_NS.iri.concat("string"),
  boolean: XSD_NS.iri.concat("boolean"),
  decimal: XSD_NS.iri.concat("decimal"),
  integer: XSD_NS.iri.concat("integer"),
  double: XSD_NS.iri.concat("double"),
  float: XSD_NS.iri.concat("float"),
  date: XSD_NS.iri.concat("date"),
  time: XSD_NS.iri.concat("time"),
  dateTime: XSD_NS.iri.concat("dateTime"),
  dateTimeStamp: XSD_NS.iri.concat("dateTimeStamp"),
  gYear: XSD_NS.iri.concat("gYear"),
  gMonth: XSD_NS.iri.concat("gMonth"),
  gDay: XSD_NS.iri.concat("gDay"),
  gYearMonth: XSD_NS.iri.concat("gYearMonth"),
  gMonthDay: XSD_NS.iri.concat("gMonthDay"),
  duration: XSD_NS.iri.concat("duration"),
  yearMonthDuration: XSD_NS.iri.concat("yearMonthDuration"),
  dayTimeDuration: XSD_NS.iri.concat("dayTimeDuration"),
  byte: XSD_NS.iri.concat("byte"),
  short: XSD_NS.iri.concat("short"),
  int: XSD_NS.iri.concat("int"),
  long: XSD_NS.iri.concat("long"),
  unsignedByte: XSD_NS.iri.concat("unsignedByte"),
  unsignedShort: XSD_NS.iri.concat("unsignedShort"),
  unsignedInt: XSD_NS.iri.concat("unsignedInt"),
  unsignedLong: XSD_NS.iri.concat("unsignedLong"),
  positiveInteger: XSD_NS.iri.concat("positiveInteger"),
  nonNegativeInteger: XSD_NS.iri.concat("nonNegativeInteger"),
  negativeInteger: XSD_NS.iri.concat("negativeInteger"),
  nonPositiveInteger: XSD_NS.iri.concat("nonPositiveInteger"),
  hexBinary: XSD_NS.iri.concat("hexBinary"),
  base64Binary: XSD_NS.iri.concat("base64Binary"),
  anyURI: XSD_NS.iri.concat("anyURI"),
  language: XSD_NS.iri.concat("language"),
  normalizedString: XSD_NS.iri.concat("normalizedString"),
  token: XSD_NS.iri.concat("token"),
  NMTOKEN: XSD_NS.iri.concat("NMTOKEN"),
  Name: XSD_NS.iri.concat("Name"),
  NCName: XSD_NS.iri.concat("NCName"),
}
