export const FOAF = {
    Agent: "http://xmlns.com/foaf/0.1/Agent",
    Person: "http://xmlns.com/foaf/0.1/Person",
    Document: "http://xmlns.com/foaf/0.1/Document",
    Organization: "http://xmlns.com/foaf/0.1/Organization",
    Group: "http://xmlns.com/foaf/0.1/Group",
    Image: "http://xmlns.com/foaf/0.1/Image",
    homepage: "http://xmlns.com/foaf/0.1/homepage",
    isPrimaryTopicOf: "http://xmlns.com/foaf/0.1/isPrimaryTopicOf",
    knows: "http://xmlns.com/foaf/0.1/knows",
    made: "http://xmlns.com/foaf/0.1/made",
    maker: "http://xmlns.com/foaf/0.1/maker",
    mbox: "http://xmlns.com/foaf/0.1/mbox",
    member: "http://xmlns.com/foaf/0.1/member",
    page: "http://xmlns.com/foaf/0.1/page",
    primaryTopic: "http://xmlns.com/foaf/0.1/primaryTopic",
    weblog: "http://xmlns.com/foaf/0.1/weblog",
  } as const; 
