const iri = "http://www.w3.org/2001/XMLSchema#";

export const XSD = {
  namespace: {
    iri,
    prefix: "xsd",
  },
  string: iri.concat("string"),
  boolean: iri.concat("boolean"),
  decimal: iri.concat("decimal"),
  integer: iri.concat("integer"),
  double: iri.concat("double"),
  float: iri.concat("float"),
  date: iri.concat("date"),
  time: iri.concat("time"),
  dateTime: iri.concat("dateTime"),
  dateTimeStamp: iri.concat("dateTimeStamp"),
  gYear: iri.concat("gYear"),
  gMonth: iri.concat("gMonth"),
  gDay: iri.concat("gDay"),
  gYearMonth: iri.concat("gYearMonth"),
  gMonthDay: iri.concat("gMonthDay"),
  duration: iri.concat("duration"),
  yearMonthDuration: iri.concat("yearMonthDuration"),
  dayTimeDuration: iri.concat("dayTimeDuration"),
  byte: iri.concat("byte"),
  short: iri.concat("short"),
  int: iri.concat("int"),
  long: iri.concat("long"),
  unsignedByte: iri.concat("unsignedByte"),
  unsignedShort: iri.concat("unsignedShort"),
  unsignedInt: iri.concat("unsignedInt"),
  unsignedLong: iri.concat("unsignedLong"),
  positiveInteger: iri.concat("positiveInteger"),
  nonNegativeInteger: iri.concat("nonNegativeInteger"),
  negativeInteger: iri.concat("negativeInteger"),
  nonPositiveInteger: iri.concat("nonPositiveInteger"),
  hexBinary: iri.concat("hexBinary"),
  base64Binary: iri.concat("base64Binary"),
  anyURI: iri.concat("anyURI"),
  language: iri.concat("language"),
  normalizedString: iri.concat("normalizedString"),
  token: iri.concat("token"),
  NMTOKEN: iri.concat("NMTOKEN"),
  Name: iri.concat("Name"),
  NCName: iri.concat("NCName"),
};
